name: 'summarizr'
description: 'An experimental knowledge gathering bot for later projects'
author: Cristopher Namchee
inputs:
  access_token:
    required: true
    description: GitHub Personal Access Token
  openai_key:
    required: true
    description: OpenAI API Key
  temperature:
    required: false
    description: GPT's temperature
    default: 0.5
  max_tokens:
    required: false
    description: Maximum token length for issue summarization
    default: 200
  model:
    required: false
    description: AI model to be used when interacting with OpenAI. Only allows fine-tunable models
    default: ada
runs:
  using: 'node20'
  main: 'dist/index.js'
