name: 'summarizr'
description: 'An experimental knowledge gathering bot for later projects'
author: 'Cristopher'
inputs:
  access_token:
    required: true
    description: 'GitHub Personal Access Token'
  openai_key:
    required: true
    description: 'OpenAI API Key'
  temperature:
    required: false
    description: GPT's temperature
    default: 0.5
  max_tokens:
    required: false
    description: Maximum token length for issue summarization
    default: 200
runs:
  using: 'node20'
  main: 'dist/index.js'
