name: summarizr
description: An experimental knowledge gathering bot for later projects
author: Cristopher Namchee
inputs:
  access_token:
    required: true
    description: GitHub Personal Access Token
  api_key:
    required: true
    description: API Key
  model_provider:
    required: false
    description: Model provider
    default: openai
  summarization_model:
    required: false
    description: Model to be used for summarization
    default: gpt-3.5-turbo
  embedding_model:
    required: false
    description: Model to be used for text embeddings
    default: text-embedding-ada-002
  max_tokens:
    required: false
    description: Maximum tokens for summarization
    default: 250
  max_issues:
    required: false
    description: Maximum number of similar issues to be returned
    default: 3
  similarity_threshold:
    required: false;
    description: Minimum similarity for triaging issues
    default: 0.9
runs:
  using: 'node20'
  main: 'dist/index.js'
