name: doopliket
description: Find possible references of duplicates from new issues and discussions
author: Cristopher Namchee
inputs:
  access_token:
    required: true
    description: GitHub Personal Access Token
  api_key:
    required: true
    description: OpenAI's API Key
  model:
    required: false
    description: Model to be used for calculating similarities
    default: text-embedding-ada-002
  max_issues:
    required: false
    description: Maximum number of similar issues to be returned
    default: 3
  min_similarity:
    required: false
    description: Minimum similarity for issues to be considered as similar
    default: 0.9
  discussions:
    required: false
    description: Include GitHub discussions when searching duplicates
    default: true
  show_similarity:
    required: false
    description: Print similarity value to the output
    default: false
  label:
    required: false
    description: Label to be added on potential duplicates
    default: ''
  template:
    required: false
    description: Message template to be used on duplicate issue or discussion. Uses mustache templating.
    default: ''
runs:
  using: 'node20'
  main: 'dist/main.js'
