name: Add new knowledge for auto-triaging

on:
  issue_comment:
    types: [created]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Summarize issue and add new knowledge
        uses: ./
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          openai_key: ${{ secrets.OPENAI_KEY }}
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
    
