name: Triage new discussion for duplicates

on:
  discussion:
    types: [created]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Triage discussion
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.OPENAI_KEY }}
