name: Triage new discussion for duplicates

on:
  discussion:
    types: [created]

jobs:
  dupliket:
    runs-on: ubuntu-latest
    steps:
      - name: Triage discussion
        uses: Namchee/dupliket@v1.0.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.OPENAI_KEY }}
