name: Detect possible duplicated issue

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Find similar issues
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.OPENAI_KEY }}
