name: Add or remove knowledge for Duplikat

on:
  issue_comment:
    types: [created]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Summarize issue and add new knowledge
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.OPENAI_KEY }}
