name: Triage new issues for duplicates

on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Triage issues
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.OPENAI_KEY }}
