name: Triage new issues for duplicates

on:
  issues:
    types: [opened]

jobs:
  dupliket:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }} # Do not listen to pull request events
    steps:
      - name: Triage issues
        uses: Namchee/dupliket@v1.0.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.OPENAI_KEY }}
